//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaTecnicaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Direccion
    {
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
