//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaTecnicaWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViaTecnicaEntities : DbContext
    {
        public ViaTecnicaEntities()
            : base("name=ViaTecnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Cliente_Direccion> Cliente_Direccion { get; set; }
        public virtual DbSet<Cliente_Email> Cliente_Email { get; set; }
        public virtual DbSet<Cliente_Telefono> Cliente_Telefono { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Turno_Cabecera> Turno_Cabecera { get; set; }
        public virtual DbSet<Turno_Detalle> Turno_Detalle { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
