//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaTecnicaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno_Detalle
    {
        public int Id { get; set; }
        public int Id_Turno_Cabecera { get; set; }
        public Nullable<int> Id_Servicio { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public string Observacion { get; set; }
    
        public virtual Servicios Servicios { get; set; }
        public virtual Turno_Cabecera Turno_Cabecera { get; set; }
    }
}
