//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaTecnicaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno_Cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno_Cabecera()
        {
            this.Turno_Detalle = new HashSet<Turno_Detalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Turno { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion_Turno { get; set; }
        public string Direccion { get; set; }
        public string Telefono_Principal { get; set; }
        public string Telefono_Secundario { get; set; }
        public string Email { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno_Detalle> Turno_Detalle { get; set; }
    }
}
